"""
build_vocab.py -- derive the REAL long-tailed interpretation vocabulary from the
BrEaST 'Interpretation' column (multi-label, '&'-separated), compute head/medium/
tail tiers by frequency and the imbalance factor, and (over)write vocab.py.

    exec(open('build_vocab.py').read())

Run this BEFORE make_manifest / build_index. After it writes vocab.py, do
Runtime > Restart, then run the pipeline so the fresh vocab is imported.
"""
import os, glob, re
from collections import Counter
import numpy as np
import pandas as pd

DATA_DIR = "./dataset"
CLINICAL_GLOB = "*clinical*"
VOCAB_PATH = "vocab.py"


def load_table(path):
    for reader in (lambda p: pd.read_excel(p, engine="openpyxl"),
                   lambda p: pd.read_excel(p),
                   lambda p: pd.read_csv(p)):
        try:
            return reader(path)
        except Exception:
            continue
    raise RuntimeError(f"Could not read {path}")


def norm_interp(s):
    s = str(s).lower().strip()
    s = re.sub(r"[()]", " ", s)
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def main():
    clinical = glob.glob(os.path.join(DATA_DIR, CLINICAL_GLOB))[0]
    df = load_table(clinical)
    col = next(c for c in df.columns if c.lower().replace(" ", "_") == "interpretation")

    # per-case multi-label interpretation lists
    per_case = []
    for v in df[col]:
        if pd.isna(v) or not str(v).strip():
            per_case.append(["normal"])
        else:
            per_case.append([norm_interp(x) for x in str(v).split("&") if x.strip()])

    counts = Counter(t for labs in per_case for t in labs)
    terms = [t for t, _ in counts.most_common()]           # sorted freq desc
    c = np.array([counts[t] for t in terms])

    # frequency-tercile tiers
    q33, q66 = np.quantile(c, 1/3), np.quantile(c, 2/3)
    tier = {}
    for t in terms:
        n = counts[t]
        tier[t] = "head" if n >= q66 else ("tail" if n <= q33 else "medium")

    imb = c.max() / c.min()
    print(f"Unique interpretation terms: {len(terms)}")
    print(f"Imbalance factor (max/min): {c.max()}/{c.min()} = {imb:.1f}")
    print("\nTop 5:", [(t, counts[t]) for t in terms[:5]])
    print("Bottom 5:", [(t, counts[t]) for t in terms[-5:]])
    from collections import Counter as C
    print("Per-tier term counts:", dict(C(tier.values())))

    body = (
        '"""vocab.py -- AUTO-GENERATED by build_vocab.py from BrEaST Interpretation."""\n'
        "import re\n\n"
        "TERMS = [\n" + "".join(f"    {t!r},\n" for t in terms) + "]\n\n"
        "TIER = {\n" + "".join(f"    {t!r}: {tier[t]!r},\n" for t in terms) + "}\n\n"
        'FIELD_OF = {t: "findings" for t in TERMS}\n\n'
        "SYNONYMS = {t: [t] for t in TERMS}\n\n"
        'FIELD_TEMPLATE = (\n'
        '    "Tissue composition: {tissue}. "\n'
        '    "Shape and margin: {shape}. "\n'
        '    "Findings: {findings}."\n'
        ")\n\n"
        "def norm_interp(s):\n"
        "    s = str(s).lower().strip()\n"
        '    s = re.sub(r"[()]", " ", s)\n'
        '    s = re.sub(r"[^a-z0-9 ]", " ", s)\n'
        '    s = re.sub(r"\\s+", " ", s).strip()\n'
        "    return s\n\n"
        "def tiers_of(terms):\n"
        "    return [TIER[t] for t in terms if t in TIER]\n"
    )
    with open(VOCAB_PATH, "w") as f:
        f.write(body)
    print(f"\nWrote {VOCAB_PATH} with {len(terms)} terms. "
          f"Now Runtime > Restart, then run the pipeline.")


if __name__ == "__main__":
    main()
