"""
build_gen_vocab.py -- derive the word-level generation vocabulary from the
manifest's report_text (already built by make_manifest_breast.py), and write
gen_vocab.py. The BrEaST reports are fully templated three-field text with a
tiny closed vocabulary (~80 words), so a from-scratch word-level tokenizer
with tied embeddings is a good fit for the ViT+Transformer-decoder generator.

Run order: make_manifest_breast.py -> this -> train_generator.py
"""
import re
from collections import Counter
import pandas as pd
import config

GEN_VOCAB_PATH = "gen_vocab.py"

PAD, BOS, EOS, UNK = "<pad>", "<bos>", "<eos>", "<unk>"
SPECIAL = [PAD, BOS, EOS, UNK]

_TOK_RE = re.compile(r"[a-z0-9']+|[.,:\-]")


def tokenize(text):
    return _TOK_RE.findall(str(text).lower())


def main():
    df = pd.read_csv(config.MANIFEST_CSV)
    counts = Counter()
    max_len = 0
    for t in df["report_text"]:
        toks = tokenize(t)
        counts.update(toks)
        max_len = max(max_len, len(toks))

    tokens = SPECIAL + sorted(counts)
    print(f"Report vocab: {len(tokens)} tokens ({len(counts)} corpus words + "
          f"{len(SPECIAL)} special)")
    print(f"Longest tokenized report: {max_len} tokens (config.MAX_LEN={config.MAX_LEN})")
    if max_len + 2 > config.MAX_LEN:
        print(f"NOTE: longest report + <bos>/<eos> ({max_len + 2}) exceeds "
              f"MAX_LEN={config.MAX_LEN}; it will be truncated at train/generate time.")

    body = (
        '"""gen_vocab.py -- AUTO-GENERATED by build_gen_vocab.py from the manifest\'s '
        'report_text."""\n'
        "import re\n\n"
        f"PAD, BOS, EOS, UNK = {PAD!r}, {BOS!r}, {EOS!r}, {UNK!r}\n\n"
        "TOKENS = [\n" + "".join(f"    {t!r},\n" for t in tokens) + "]\n\n"
        "TOKEN2ID = {t: i for i, t in enumerate(TOKENS)}\n"
        "ID2TOKEN = {i: t for i, t in enumerate(TOKENS)}\n"
        "PAD_ID, BOS_ID, EOS_ID, UNK_ID = (TOKEN2ID[PAD], TOKEN2ID[BOS], "
        "TOKEN2ID[EOS], TOKEN2ID[UNK])\n"
        "VOCAB_SIZE = len(TOKENS)\n\n"
        '_TOK_RE = re.compile(r"[a-z0-9\']+|[.,:\\-]")\n\n'
        "def tokenize(text):\n"
        "    return _TOK_RE.findall(str(text).lower())\n\n"
        "def encode(text, max_len):\n"
        "    \"\"\"BOS + content tokens (truncated) + EOS, right-padded to max_len.\"\"\"\n"
        "    ids = [BOS_ID] + [TOKEN2ID.get(t, UNK_ID) for t in tokenize(text)]\n"
        "    ids = ids[:max_len - 1] + [EOS_ID]\n"
        "    ids = ids[:max_len]\n"
        "    return ids + [PAD_ID] * (max_len - len(ids))\n\n"
        "def detokenize(ids):\n"
        "    \"\"\"Token ids -> readable string; stops at EOS, re-attaches punctuation.\"\"\"\n"
        "    toks = []\n"
        "    for i in ids:\n"
        "        t = ID2TOKEN.get(int(i), UNK)\n"
        "        if t == EOS:\n"
        "            break\n"
        "        if t in (PAD, BOS):\n"
        "            continue\n"
        "        toks.append(t)\n"
        "    out = []\n"
        "    for t in toks:\n"
        "        if t in ('.', ',', ':') and out:\n"
        "            out[-1] = out[-1] + t\n"
        "        else:\n"
        "            out.append(t)\n"
        "    return capitalize(' '.join(out))\n\n"
        "def capitalize(text):\n"
        "    \"\"\"Sentence-case: capitalise the first letter and after '. '.\"\"\"\n"
        "    parts = text.split('. ')\n"
        "    parts = [p[:1].upper() + p[1:] if p else p for p in parts]\n"
        "    return '. '.join(parts)\n"
    )
    with open(GEN_VOCAB_PATH, "w") as f:
        f.write(body)
    print(f"\nWrote {GEN_VOCAB_PATH} with {len(tokens)} tokens.")


if __name__ == "__main__":
    main()
