"""gen_vocab.py -- AUTO-GENERATED by build_gen_vocab.py from the manifest's report_text."""
import re

PAD, BOS, EOS, UNK = '<pad>', '<bos>', '<eos>', '<unk>'

TOKENS = [
    '<pad>',
    '<bos>',
    '<eos>',
    '<unk>',
    ',',
    '-',
    '.',
    '1',
    '2',
    '3',
    '4a',
    '4b',
    '4c',
    '5',
    ':',
    'abscess',
    'adenoma',
    'adenosis',
    'and',
    'angular',
    'applicable',
    'available',
    'bi',
    'breast',
    'calcifications',
    'circumscribed',
    'complex',
    'composition',
    'cyst',
    'duct',
    'dysplasia',
    'ectasia',
    'fat',
    'fibroadenoma',
    'fibroglandular',
    'filled',
    'findings',
    'fluid',
    'hamartoma',
    'hemangioma',
    'hematoma',
    'heterogeneous',
    'homogeneous',
    'implant',
    'indistinct',
    'intraductal',
    'intramammary',
    'irregular',
    'isolated',
    'lactating',
    'lacteal',
    'lipoma',
    'lymph',
    'malignancy',
    'mammary',
    'margin',
    'mastitis',
    'microlobulated',
    'necrosis',
    'node',
    'non',
    'not',
    'of',
    'oval',
    'papilloma',
    'phyllodes',
    'predominantly',
    'radiotherapy',
    'rads',
    'round',
    'rupture',
    'scar',
    'seroma',
    'shape',
    'silicone',
    'simple',
    'spiculated',
    'surgery',
    'suspicion',
    'thick',
    'tissue',
    'tumor',
    'with',
]

TOKEN2ID = {t: i for i, t in enumerate(TOKENS)}
ID2TOKEN = {i: t for i, t in enumerate(TOKENS)}
PAD_ID, BOS_ID, EOS_ID, UNK_ID = (TOKEN2ID[PAD], TOKEN2ID[BOS], TOKEN2ID[EOS], TOKEN2ID[UNK])
VOCAB_SIZE = len(TOKENS)

_TOK_RE = re.compile(r"[a-z0-9']+|[.,:\-]")

def tokenize(text):
    return _TOK_RE.findall(str(text).lower())

def encode(text, max_len):
    """BOS + content tokens (truncated) + EOS, right-padded to max_len."""
    ids = [BOS_ID] + [TOKEN2ID.get(t, UNK_ID) for t in tokenize(text)]
    ids = ids[:max_len - 1] + [EOS_ID]
    ids = ids[:max_len]
    return ids + [PAD_ID] * (max_len - len(ids))

def detokenize(ids):
    """Token ids -> readable string; stops at EOS, re-attaches punctuation."""
    toks = []
    for i in ids:
        t = ID2TOKEN.get(int(i), UNK)
        if t == EOS:
            break
        if t in (PAD, BOS):
            continue
        toks.append(t)
    out = []
    for t in toks:
        if t in ('.', ',', ':') and out:
            out[-1] = out[-1] + t
        else:
            out.append(t)
    return capitalize(' '.join(out))

def capitalize(text):
    """Sentence-case: capitalise the first letter and after '. '."""
    parts = text.split('. ')
    parts = [p[:1].upper() + p[1:] if p else p for p in parts]
    return '. '.join(parts)
