"""vocab.py -- AUTO-GENERATED by build_vocab.py from BrEaST Interpretation."""
import re

TERMS = [
    'suspicion of malignancy',
    'fibroadenoma',
    'intraductal papilloma',
    'dysplasia',
    'cyst filled with thick fluid',
    'complex cyst non simple cyst',
    'mammary duct ectasia',
    'duct filled with thick fluid',
    'hamartoma',
    'breast scar surgery',
    'mastitis',
    'silicone implant',
    'not applicable',
    'simple cyst',
    'intramammary lymph node',
    'hematoma',
    'lipoma',
    'adenosis',
    'phyllodes tumor',
    'implant rupture',
    'lacteal cyst',
    'fat necrosis',
    'breast scar radiotherapy',
    'isolated calcifications',
    'abscess',
    'hemangioma',
    'seroma',
    'lactating adenoma',
]

TIER = {
    'suspicion of malignancy': 'head',
    'fibroadenoma': 'head',
    'intraductal papilloma': 'head',
    'dysplasia': 'head',
    'cyst filled with thick fluid': 'head',
    'complex cyst non simple cyst': 'head',
    'mammary duct ectasia': 'head',
    'duct filled with thick fluid': 'head',
    'hamartoma': 'head',
    'breast scar surgery': 'head',
    'mastitis': 'head',
    'silicone implant': 'medium',
    'not applicable': 'medium',
    'simple cyst': 'medium',
    'intramammary lymph node': 'medium',
    'hematoma': 'medium',
    'lipoma': 'medium',
    'adenosis': 'tail',
    'phyllodes tumor': 'tail',
    'implant rupture': 'tail',
    'lacteal cyst': 'tail',
    'fat necrosis': 'tail',
    'breast scar radiotherapy': 'tail',
    'isolated calcifications': 'tail',
    'abscess': 'tail',
    'hemangioma': 'tail',
    'seroma': 'tail',
    'lactating adenoma': 'tail',
}

FIELD_OF = {t: "findings" for t in TERMS}

SYNONYMS = {t: [t] for t in TERMS}

FIELD_TEMPLATE = (
    "Tissue composition: {tissue}. "
    "Shape and margin: {shape}. "
    "Findings: {findings}."
)

def norm_interp(s):
    s = str(s).lower().strip()
    s = re.sub(r"[()]", " ", s)
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def tiers_of(terms):
    return [TIER[t] for t in terms if t in TIER]
